site_name: Alabaster
theme_dir: mkdocs_alabaster
copyright: 2016 Alexander Pushkov

pages:
  - Home: index.md
  - User Guide: guide.md
  - License: license.md

markdown_extensions:
  - toc:
      permalink: "¶"

extra:
  logo: logo.png
  include_toc: yes
  extra_nav_links:
    Fork me on GitHub: https://github.com/iamale/mkdocs-alabaster
